import { DIAGRAM_HEIGHT, DIAGRAM_WIDTH, type VesselDiagramConfig, type ZoneMarker } from './types';
export interface PixelRect { x:number; y:number; width:number; height:number }
interface ImageSource { width:number; height:number; naturalWidth?:number; naturalHeight?:number; close?:()=>void }
interface CanvasContext { fillStyle:string|CanvasGradient|CanvasPattern; strokeStyle:string|CanvasGradient|CanvasPattern; lineWidth:number; fillRect(x:number,y:number,w:number,h:number):void; drawImage(image:ImageSource,x:number,y:number,w:number,h:number):void; beginPath():void; ellipse(x:number,y:number,rx:number,ry:number,r:number,s:number,e:number):void; fill():void; stroke():void; strokeRect(x:number,y:number,w:number,h:number):void }
interface CanvasLike { getContext(kind:'2d'):CanvasContext|null; toBlob(callback:(blob:Blob|null)=>void,type?:string):void }
export interface ComposeDependencies { decodeImage?:(file:File)=>Promise<ImageSource>; createCanvas?:(width:number,height:number)=>CanvasLike|null; createImageBitmap?:(file:File)=>Promise<ImageSource>; createObjectURL?:(file:File)=>string; revokeObjectURL?:(url:string)=>void; loadImage?:(url:string)=>Promise<ImageSource> }
export function fitContain(sourceWidth:number,sourceHeight:number,targetWidth:number,targetHeight:number):PixelRect { const scale=Math.min(targetWidth/sourceWidth,targetHeight/sourceHeight),width=sourceWidth*scale,height=sourceHeight*scale; return {x:(targetWidth-width)/2,y:(targetHeight-height)/2,width,height}; }
async function decode(file:File,deps:ComposeDependencies):Promise<ImageSource> { if(deps.decodeImage)return deps.decodeImage(file); const bitmap=deps.createImageBitmap??(typeof globalThis.createImageBitmap==='function'?globalThis.createImageBitmap.bind(globalThis):undefined); if(bitmap)return bitmap(file); const createUrl=deps.createObjectURL??((value:File)=>URL.createObjectURL(value)),revoke=deps.revokeObjectURL??((url:string)=>URL.revokeObjectURL(url)); const load=deps.loadImage??((url:string)=>new Promise<ImageSource>((resolve,reject)=>{if(typeof document==='undefined')return reject(new Error('no document'));const image=document.createElement('img');image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('image load failed'));image.src=url;})); const url=createUrl(file);try{return await load(url)}finally{revoke(url)} }
function fail(code:string):never{throw new Error(code)}
export async function composeVesselDiagram(config:VesselDiagramConfig,markerIds:string[],deps:ComposeDependencies={}):Promise<Uint8Array>{let image:ImageSource;try{image=await decode(config.imageFile,deps)}catch{fail('VESSEL_IMAGE_DECODE_FAILED')}try{let canvas:CanvasLike|null;try{canvas=(deps.createCanvas??((w:number,h:number)=>{if(typeof document==='undefined')return null;const e=document.createElement('canvas');e.width=w;e.height=h;return e}))(DIAGRAM_WIDTH,DIAGRAM_HEIGHT)}catch{fail('VESSEL_CANVAS_UNAVAILABLE')}if(!canvas)fail('VESSEL_CANVAS_UNAVAILABLE');const context=canvas.getContext('2d');if(!context)fail('VESSEL_CANVAS_UNAVAILABLE');context.fillStyle='#ffffff';context.fillRect(0,0,DIAGRAM_WIDTH,DIAGRAM_HEIGHT);const rect=fitContain(image.naturalWidth??image.width,image.naturalHeight??image.height,DIAGRAM_WIDTH,DIAGRAM_HEIGHT);context.drawImage(image,rect.x,rect.y,rect.width,rect.height);const markers=new Map([...config.hullMarkers,...config.nicheMarkers].map(m=>[m.id,m]));context.fillStyle='rgba(230, 64, 64, 0.32)';context.strokeStyle='#d83b3b';context.lineWidth=4;for(const id of markerIds){const marker=markers.get(id);if(marker)drawMarker(context,marker)}let blob:Blob|null;try{blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/png'))}catch{fail('VESSEL_PNG_ENCODE_FAILED')}if(!blob)fail('VESSEL_PNG_ENCODE_FAILED');try{return new Uint8Array(await blob.arrayBuffer())}catch{fail('VESSEL_PNG_ENCODE_FAILED')}}finally{image.close?.()}}
function drawMarker(context:CanvasContext,marker:ZoneMarker):void{const{x,y,width,height}=marker.rect,px=x*DIAGRAM_WIDTH,py=y*DIAGRAM_HEIGHT,pw=width*DIAGRAM_WIDTH,ph=height*DIAGRAM_HEIGHT;if(marker.shape==='RECTANGLE'){context.fillRect(px,py,pw,ph);context.strokeRect(px,py,pw,ph);return}context.beginPath();context.ellipse(px+pw/2,py+ph/2,pw/2,ph/2,0,0,Math.PI*2);context.fill();context.stroke()}
