import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import JSZip from 'jszip';
const stage=(page:Page,index:number)=>page.getByRole('navigation',{name:'Report stages'}).getByRole('button').nth(index);
test('personnel DB, numeric diagrams, custom rectangles, photo gaps and final summary editing',async({page})=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>void d.accept());
 await page.goto('/');
 await page.getByRole('button',{name:'조회 없이 선박 정보 직접 입력'}).click();
 await page.getByLabel('직접 입력 name',{exact:true}).fill('QA EDITING VESSEL');
 await page.getByLabel('직접 입력 imo',{exact:true}).fill('1234567');
 await page.getByRole('button',{name:'Removal 작업 선택'}).click();
 await page.getByRole('button',{name:'FWD PORT 작업 배정',exact:true}).click();
 await page.getByLabel('Niche component').selectOption('Bilge Keel');
 await page.getByLabel('Niche type',{exact:true}).selectOption('SINGLE');
 await page.getByRole('button',{name:/Scope 추가$/}).click();
 await page.getByRole('button',{name:/Scope 만들기$/}).click();
 await page.getByRole('button',{name:'Report Information 입력',exact:true}).click();
 await page.getByLabel('Diver search').fill('QA New Diver');
 await page.getByRole('button',{name:/새 인원 등록/}).click();
 await page.getByRole('button',{name:'DB 저장 후 보고서에 추가'}).click();
 await expect(page.getByRole('cell',{name:'QA New Diver',exact:true})).toBeVisible();
 await page.screenshot({path:'outputs/usability-information.png',fullPage:true});
 await stage(page,3).click();await page.getByLabel('선박 사이드뷰 이미지').setInputFiles('e2e/fixtures/vessel-side.png');
 await page.getByLabel('도면 가로 크기 숫자',{exact:true}).fill('120');await page.getByLabel('도면 가로 크기 숫자',{exact:true}).press('Tab');
 await expect(page.getByLabel('도면 가로 크기 숫자',{exact:true})).toHaveValue('120');
 await page.getByRole('button',{name:'Niche 맞추기로 이동'}).click();
 await page.getByRole('button',{name:'표식 추가',exact:true}).click();
 const marker=page.getByRole('dialog',{name:'표식 추가·수정'});
 await marker.getByLabel('표식 이름').fill('QA Bilge rectangle');await marker.getByLabel('모양').selectOption('RECTANGLE');
 await marker.getByRole('checkbox',{name:/BILGE KEEL.*연결/}).check();
 await marker.getByRole('button',{name:'표식 저장'}).click();
 await expect(page.getByRole('button',{name:'QA Bilge rectangle 표식',exact:true})).toBeVisible();
 await page.screenshot({path:'outputs/usability-markers.png',fullPage:true});
 await page.getByRole('button',{name:'선박 위치도 설정 완료'}).click();await page.getByRole('button',{name:'Report Input으로',exact:true}).click();
 await page.getByRole('button',{name:'BEFORE 새 사진 추가',exact:true}).click();
 const bytes=await readFile('e2e/fixtures/vessel-side.png');
 await page.getByLabel('보고서 사진 추가 파일').setInputFiles(['A','B','C'].map(name=>({name:`${name}.png`,mimeType:'image/png',buffer:bytes})));
 const cards=page.getByRole('region',{name:'BEFORE 사진 갤러리'}).locator('.photo-row');
 await cards.first().scrollIntoViewIfNeeded();
 const from=await cards.nth(0).boundingBox();const to=await cards.nth(1).boundingBox();expect(from&&to).toBeTruthy();
 // Drive HTML5 drag events directly to avoid Edge's native OS image-drag loop
 // blocking the test transport. Coordinates still exercise the actual edge resolver.
 const transfer=await page.evaluateHandle(()=>new DataTransfer());
 await cards.nth(0).dispatchEvent('dragstart',{dataTransfer:transfer});
 await cards.nth(1).dispatchEvent('dragover',{dataTransfer:transfer,clientX:to!.x+to!.width-4,clientY:to!.y+60});
 await expect(cards.nth(1)).toHaveClass(/insert-after/);
 await page.screenshot({path:'outputs/usability-photo-gap.png',fullPage:true});
 await cards.nth(1).dispatchEvent('drop',{dataTransfer:transfer,clientX:to!.x+to!.width-4,clientY:to!.y+60});
 await transfer.dispose();
 await expect(cards.nth(0)).toContainText('B.png');await expect(cards.nth(1)).toContainText('A.png');
 for(let i=0;i<3;i++)await cards.first().getByRole('button',{name:/미배정/}).click();
 await page.getByRole('button',{name:'미배정 사진 3',exact:true}).click();
 await page.getByRole('button',{name:'미배정 사진 4열'}).click();
 await expect(page.locator('.unmatched-list')).toHaveCSS('grid-template-columns',/\d+.*\d+.*\d+.*\d+/);
 await page.screenshot({path:'outputs/usability-photos-4cols.png',fullPage:true});
 await stage(page,7).click();
 await expect(page.getByRole('table',{name:'MAIN HULL Finding Matrix'})).toBeVisible();
 const niche=page.getByRole('table',{name:'NICHE Finding Matrix'});await expect(niche.getByText('Rope Guard',{exact:true})).toHaveCount(0);
 await niche.getByRole('button',{name:/컨디션 수정/}).click();
 await page.getByLabel('수정할 원본 구역').selectOption({index:1});
 await page.getByLabel('서머리 fouling coverage').fill('23');await page.getByRole('button',{name:'원본에 저장'}).click();
 await expect(niche.getByText('23%',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'결과 문구 수정'}).click();await page.getByLabel('결과 제목').fill('QA FULL LENGTH TITLE — Vessel inspection, removal and final recorded condition across all serviced components');
 await page.screenshot({path:'outputs/usability-result-dialog.png',fullPage:true});await page.getByRole('button',{name:'문구 저장',exact:true}).click();
 await page.screenshot({path:'outputs/usability-summary.png',fullPage:true});
 const typeCell=niche.locator('tbody tr').first().locator('td').nth(3);
 expect((await typeCell.boundingBox())!.width).toBeGreaterThan(150);
 await page.setViewportSize({width:1024,height:900});
 await page.screenshot({path:'outputs/usability-summary-1024.png',fullPage:true});
 expect((await typeCell.boundingBox())!.width).toBeGreaterThan(150);
 const lastRow=await niche.locator('tbody tr').last().boundingBox();
 const actions=await page.locator('.summary-actions').boundingBox();
 expect(actions!.y).toBeGreaterThanOrEqual(lastRow!.y+lastRow!.height);
 await page.setViewportSize({width:1440,height:1000});
 await stage(page,3).click();await page.getByLabel('도면 가로 크기 숫자',{exact:true}).fill('110');await page.getByLabel('도면 가로 크기 숫자',{exact:true}).press('Tab');
 await stage(page,8).click();await page.getByRole('button',{name:'최종 Word 준비'}).click();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Word 보고서 다운로드',exact:true}).click();const download=await downloadPromise;await download.saveAs('outputs/usability-incomplete.docx');
 const xml=await(await JSZip.loadAsync(await readFile('outputs/usability-incomplete.docx'))).file('word/document.xml')!.async('string');
 expect(xml).toContain('23%');expect(xml).not.toContain('vessel_profile');expect(xml).toContain('QA FULL LENGTH TITLE');
 await stage(page,1).click();await page.getByLabel('Diver search').fill('QA New Diver');await expect(page.getByRole('cell',{name:'QA New Diver',exact:true})).toBeVisible();
 expect(errors).toEqual([]);
});
